### ISSUE TITLE
Not all open files being shown in the list

### ISSUE THREAD

**Issue by Clavus** [Ant-f/WorkingFilesList#14]
I've noticed this issue quite a lot when working with VS and Unity game engine. Not too sure what causes it. Possibly caused by the fact Unity changes the VS project from the outside? When I select a file that isn't shown in the list, it appears in the list again. Sometimes when I close a file, the list refreshes and shows everything again. VS 15.5.4, Unity 2018.1.2.

![bug](https://user-images.githubusercontent.com/670995/41096227-3d2ffaa4-6a54-11e8-937c-683beb8ef85a.jpg)

**Comment by Ant-f** [comment]
I've not worked with a Unity project before; could you explain what you mean when you say Unity changes the VS project from the outside? Does it have an editor external to VS? Is VS always in focus (i.e. the active application) when the VS code-editor-window is opened?

Is there a specific type of file that always doesn't get added to Working Files List the first time, or only sometimes? Or is it a normal `.cs` files that sometimes gets added, and other times not?

**Comment by Clavus** [comment]
I'm not too sure how Unity actually does things in that regard. It generates the Visual Studio project when you add or delete scripts in the Unity Editor.

I found a consistent way to reproduce this issue is to create a new C# script in Unity, double click to open it, which re-focuses on Visual Studio (having configured Unity to use VS as default code editor of course). Working Files List shows only that new script and a few others (don't know why those specifically) in the list, until I close the new file, after which the list suddenly shows all open files again.

**Comment by Ant-f** [comment]
When you double click the script (causing Visual Studio to refocus) is it a new instance? If not, does it reload the VS solution?

You also mentioned that only the new script and a few others are in Working Files List. Do you mean that some of the items previously in the list have gone, or that many new code windows have opened in VS but of those only a few are initially shown in Working Files List?

**Comment by Clavus** [comment]
When you double click the script in Unity, it simply opens that file in Visual Studio, within the project if VS is already open. Every time you create a new script in Unity it refreshes the project I think.

And for the second thing: yes, a lot of the items that were previously in the list disappear but a few usually remain (plus the one you actually created & opened from Unity). I can't really see why those remain specifically.

I've made a recording to show what happens:
[2018-06-14 00-26-49.zip](https://github.com/Ant-f/WorkingFilesList/files/2100185/2018-06-14.00-26-49.zip)

**Comment by Ant-f** [comment]
Thanks for the recording. It's much easier to see what's going on.

It looks like when a new script is created in Unity, Unity somehow modifies/rewrites the `.csproj`/`.sln` file and VS unloads and reloads it. I suspect this because the whole _Framework_ project disappears from Working Files List. When it reappears it is a different colour, suggesting it is a previously unopened project as far as Working Files List is concerned.

I've tried to recreate/simulate this by creating a VS solution, and then modifying a `.csproj` file within a text editor. When I refocus on VS (2017), I get a dialog asking whether I want to reload the solution; I noticed that this (the dialog popping up) doesn't happen in the recording. Do you have a setting/extension that auto-reloads changed `.csproj` project files? I can find a similar option, but it only applies to files, and changes to projects are always prompted for me.

**Comment by Clavus** [comment]
Hm, I noticed this might be a feature for the Visual Studio Tools for Unity (which you can get through Visual Studio Installer as a component for VS). In the past people used to see that "reload project" prompt pop up all the time. At some point they added an auto-reload feature:
![image](https://user-images.githubusercontent.com/670995/41434803-3f820472-701d-11e8-9391-6b27c94685cd.png)
So I guess this might be the cause?

**Comment by Ant-f** [comment]
Am I right in saying that some `.csproj` files are dynamically generated by Unity? If so, and they differ from 'normal' `.csproj` files, would you be able to post a sample (just open it in a text editor and copy/paste the contents)? It can be a sample one with just one file reference.

**Comment by Ant-f** [comment]
I've managed to recreate the issue, but it isn't as easy to fix as I would have hoped. Working Files List maintains synchronisation by listening to events such as when Visual Studio windows are created, and closed, for example. When a Unity project is overwritten, it is effectively removed from the solution and any of its open files are closed. Working Files List listens for these events, and behaves accordingly; that's why the file entries disappear.

Without Unity _Automatic project reloading_ enabled, project files being removed have any open editor windows closed. When this setting is enabled however, the editor windows remain open even though events are sent to indicate that they have been closed. This creates a disparity between the editor windows actually open, and the files displayed by Working Files List. There are events available for projects being added, and files being loaded (but not when they have actually finished loading); this makes the latter unsuitable for knowing when to trigger a synchronisation.

I can however use the former, and add a small delay between the project being loaded before triggering a synchronisation; I've tried this and it seems to work. The delay would be to allow all files within the project to fully load. As there is no event to know when all files have been fully loaded, there is no guarantee that doing this will work 100% of the time, and may cause Working Files List to 'flicker' (depending on the duration of the delay). However, it should avoid the situation where you have to manually close a file in order for all files to display correctly.

**Comment by Ant-f** [comment]
This has been included in version 1.3. I've defaulted the delay to be 100ms, but it can be configured in the Options page. I don't work with Unity projects, so I don't know if there's a better value to default it to. If there is, let me know and I can change it in a future release.
