### ISSUE TITLE
External headers not shown in list

### ISSUE THREAD

**Issue by Osse** [Ant-f/WorkingFilesList#18]
I saw [this report](https://github.com/Ant-f/WorkingFilesList/issues/14) but I think my issue is different.

In a simple file with `#include <iostream>` selecting Open Doucment (Ctrl + Shift + G by default) on `iostream` does not add a new file to the working files list. It does however open a new tab.

This may be by design. After all `iostream`is not a part of any open solution. I see there is a "Miscellaneous Files" group in the file list but it's not apparent to me when a file is added to it or not. It would be nice with a setting to show all open files in the list, so that there's effectively a 1:1 correspondence between the list and the tabs.

**Comment by Ant-f** [comment]
If I understand correctly, what you’re describing doesn’t sound like it was intentionally by design as such.

Working Files List uses the Visual Studio automation object to both find out about any files that are open, and to manipulate (e.g. open in the editor/close) them. The file groups are the names of the parent projects, as discovered though the automation object; if a file does not belong to any project, it will belong to _Miscellaneous Files_. [For example, if you open a text file in Visual Studio from Windows Explorer, it should open in a new instance of Visual Studio under the group _Miscellaneous Files_].

Occasionally there are some files that Working Files List cannot manipulate (e.g. maybe the file was deleted externally from Visual Studio while the solution was still open). In order to avoid having orphaned entries in Working Files List, it removes any entries that might be problematic.

This does seem different from issue #14, as from what I understand _iostream_ does not reappear. It seems more like, for whatever reason, Working Files List cannot find/access _iostream_. I haven’t worked much with C++ lately so sorry if the answers to these questions are obvious; could it be that _iostream_ is in a system folder (e.g. Program Files) that Visual Studio doesn’t have access to [maybe try running Visual Studio as an administrator]? Alternatively, could it be that _iostream_ doesn’t exist as a file on disk [e.g. it might be a file within memory, extracted from a .dll library]?

**Comment by Ant-f** [comment]
Closing issue after eight days of inactivity; will reopen if necessary.
